# Generated by Django 2.2.3 on 2019-07-18 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentation',
            name='docfile',
            field=models.FileField(default=None, max_length=255, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='documentation',
            name='url',
            field=models.URLField(default=None, max_length=255, null=True),
        ),
    ]
