# Generated by Django 2.2.3 on 2019-07-26 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
        ('documentation', '0002_auto_20190718_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentation',
            name='asset',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='asset.Asset'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='documentation',
            name='docfile',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='documentation',
            name='url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
