# Generated by Django 2.2.3 on 2019-07-26 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0003_auto_20190726_1117'),
        ('documentation', '0003_auto_20190726_1107'),
    ]

    operations = [
    ]
