# Generated by Django 2.2.3 on 2019-07-26 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0004_merge_20190726_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentation',
            name='docfile',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='documentations'),
        ),
    ]
