# Generated by Django 2.2.3 on 2019-07-26 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0005_auto_20190726_1145'),
        ('documentation', '0005_auto_20190726_1144'),
    ]

    operations = [
    ]
