# Generated by Django 2.2.3 on 2019-07-26 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_auto_20190726_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='webSite',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
