# Generated by Django 2.2.3 on 2019-07-26 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('localisation', '0001_initial'),
        ('asset', '0002_asset_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='localisation.Room'),
            preserve_default=False,
        ),
    ]
