# Generated by Django 2.2.3 on 2019-07-29 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batiment',
            name='latitude',
            field=models.DecimalField(decimal_places=3, max_digits=25),
        ),
        migrations.AlterField(
            model_name='batiment',
            name='longitude',
            field=models.DecimalField(decimal_places=3, max_digits=25),
        ),
    ]
