# Generated by Django 2.2.3 on 2019-07-26 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batiment',
            name='lat',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=19),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='batiment',
            name='long',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=19),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='batiment',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='floor',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
