# Generated by Django 2.2.3 on 2019-07-26 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lat', models.DecimalField(decimal_places=2, max_digits=9)),
                ('Long', models.DecimalField(decimal_places=2, max_digits=9)),
                ('Name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Localization.Building')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Localization.Floor')),
            ],
        ),
    ]
