# Generated by Django 2.2.3 on 2019-07-26 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batiment',
            name='lat',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='batiment',
            name='long',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
